### ISSUE TITLE
Python 2

### ISSUE THREAD

**Issue by CurtisLeeBolin** [huntergregal/mimipenguin#29]
./mimipenguin.sh: line 59: python2: command not found

Looks like python2 needs to be added to the requirements list.

You might want to consider porting to python 3. https://pythonclock.org/

**Comment by the-useless-one** [comment]
Hi @CurtisLeeBolin 

mimipenguin was already ported to Python 3 [here](https://github.com/huntergregal/mimipenguin/blob/master/mimipenguin.py). The script is also compatible Python 2. Cheers,

Y

**Comment by CurtisLeeBolin** [comment]
The `README.md` didn't have any instructions, so I just followed the screenshot.
