### ISSUE TITLE
syntax error near unexpected token `<<<'

### ISSUE THREAD

**Issue by winnettjohnston** [huntergregal/mimipenguin#34]
## Bug report

Write a description 
When i try to execute the mimipenguin.sh script it throws the following syntax error
```
./mimipenguin.sh
./mimipenguin.sh: line 37: syntax error near unexpected token `<<<'
./mimipenguin.sh: line 37: `	done <<< "$mem_maps"'
```

#### Information
Target OS info
```
cat /etc/issue
Red Hat Linux release 7.3 (Valhalla)
Kernel \r on an \m
```

**Comment by David-5-1** [comment]
Hello,

can you run the above commands to check what Bash version you are using and force the script to be run by Bash (the syntax that raises the error is not POSIX compliant IIRC, but is supported by bash):
```
bash --version
bash mimipenguin.sh
```

**Comment by huntergregal** [comment]
closing - probably an out-dated bash
