### ISSUE TITLE
1.sh: line 19: syntax error near unexpected token `{

### ISSUE THREAD

**Issue by jackpit110** [huntergregal/mimipenguin#37]
I try to run sh file with this command : sh 1.sh But I got these errors

```
1.sh: line 2: 
: command not found
1.sh: line 6: 
: command not found
1.sh: line 19: syntax error near unexpected token `{
'
1.sh: line 19: `function dump_pid () {
'
```

OS Version : Red Hat Enterprise Linux Server release 5.7
Bash Version : GNU bash, version 3.2.25(1)-release (x86_64-redhat-linux-gnu)

Also there is no python3 installed on the server , Is there any python2 version of mimipenguin?

**Comment by bcoles** [comment]
Have you tried `bash mimipengiun.sh` ? Also, the version of Bash you're using is likely too old.

n1nj4sec has written [mimipy](https://github.com/n1nj4sec/mimipy) which I believe uses Python2.
