### ISSUE TITLE
Not working on Linux kali 4.19.0-kali5-amd64

### ISSUE THREAD

**Issue by simoncaogit** [huntergregal/mimipenguin#48]
## Bug report

Write a description 

kali:/root/mimipenguin# ./mimipenguin 
[+] GNOME KEYRING (928)
  [-] gnome-keyring-daemon version not supported
  [!] ERROR: dumping passwords from keyring
[+] GNOME KEYRING (2018)
  [-] gnome-keyring-daemon version not support

#### Information
Target OS info
- run `cat /etc/issue`
- run `ps aux | grep -e "gnome-keyring" -e gdm`

kali:/root# cat /etc/issue
Kali GNU/Linux Rolling \n \l
kali:/root# date
Wed 31 Jul 2019 03:03:58 AM EDT

kali:/root# ps aux | grep -e "gnome-keyring" -e gdm
root        832  0.0  0.3 244584  9076 ?        Ssl  Jul30   0:00 /usr/sbin/gdm3
root        864  0.0  0.3 169304  9060 ?        Sl   Jul30   0:00 gdm-session-worker [pam/gdm-autologin]
root        928  0.0  0.2 240996  6888 ?        Sl   Jul30   0:00 /usr/bin/gnome-keyring-daemon --daemonize --login
root        976  0.0  0.2 166732  6192 tty2     Ssl+ Jul30   0:00 /usr/lib/gdm3/gdm-x-session --run-script /usr/bin/gnome-session
root        978  0.0  2.1 368076 53268 tty2     Sl+  Jul30   0:02 /usr/lib/xorg/Xorg vt2 -displayfd 3 -auth /run/user/0/gdm/Xauthority -background none -noreset -keeptty -verbose 3
root       1786  0.0  0.3 169208  8684 ?        Sl   Jul30   0:00 gdm-session-worker [pam/gdm-launch-environment]
Debian-+   1802  0.0  0.2 166736  6092 tty1     Ssl+ Jul30   0:00 /usr/lib/gdm3/gdm-x-session gnome-session --autostart /usr/share/gdm/greeter/autostart
Debian-+   1804  0.0  1.9 363356 48620 tty1     Sl+  Jul30   0:00 /usr/lib/xorg/Xorg vt1 -displayfd 3 -auth /run/user/131/gdm/Xauthority -background none -noreset -keeptty -verbose 3
Debian-+   1813  0.0  0.6 574068 15244 tty1     Sl+  Jul30   0:00 /usr/lib/gnome-session/gnome-session-binary --autostart /usr/share/gdm/greeter/autostart
root       2001  0.0  0.3 169268  8800 ?        Sl   Jul30   0:00 gdm-session-worker [pam/gdm-password]
simon1     2018  0.0  0.2 241028  7400 ?        Sl   Jul30   0:00 /usr/bin/gnome-keyring-daemon --daemonize --login
simon1     2022  0.0  0.2 166732  6088 tty3     Ssl+ Jul30   0:00 /usr/lib/gdm3/gdm-x-session --run-script /usr/bin/gnome-session
simon1     2024  0.0  1.9 363808 48732 tty3     Sl+  Jul30   0:05 /usr/lib/xorg/Xorg vt3 -displayfd 3 -auth /run/user/1001/gdm/Xauthority -background none -noreset -keeptty -verbose 3
root       3140  0.0  0.0   6012   888 pts/0    S+   03:04   0:01 grep -e gnome-keyring -e gdm

### Current behavior 
Write the current behavior and/or screenshot

### Expected behavior 
Write the expected behavior and/or screenshot

## Feature request
Write a description 
#### Information
Target OS info
- run `cat /etc/issue`

### Expected behavior 
Write the expected behavior and/or screenshot

### Reproduce Steps
if you know how to do it, please explain the steps. This would help use to speed up adding this feature

**Comment by huntergregal** [comment]
2.0 release working. Mind you the 32bit fails to build as 32bit headers are not installed by default

requires running

`sudo apt-get install gcc-multilib g++-multilib`

`Linux kali 4.19.0-kali4-amd64 #1 SMP Debian 4.19.28-2kali1 (2019-03-18) x86_64 GNU/Linux`

```
root@kali:~/mimipenguin# sudo ./mimipenguin
[+] Searching: [SYSTEM - GNOME] (gdm-password)
[+] Searching: [SYSTEM - GNOME] (gnome-keyring-daemon)
  [-] root:toor
  [-] root:toor
```
