### ISSUE TITLE
Shellcheck: SC1087 (error): Use braces when expanding arrays

### ISSUE THREAD

**Issue by thomasmerz** [huntergregal/mimipenguin#53]
## Bug report
[Shellcheck](https://github.com/koalaman/shellcheck) is complaining:
```
In mimipenguin.sh line 124:
        export RESULTS="$RESULTS[HIGH]$4            $line\n"
                        ^-- SC1087 (error): Use braces when expanding arrays, e.g. ${array[idx]} (or ${var}[.. to quiet).


In mimipenguin.sh line 127:
            export RESULTS="$RESULTS[LOW]$4         $line\n"
                            ^-- SC1087 (error): Use braces when expanding arrays, e.g. ${array[idx]} (or ${var}[.. to quiet).

For more information:
  https://www.shellcheck.net/wiki/SC1087 -- Use braces when expanding arrays,...
```

### Expected behavior 
`shellcheck` should not find any error.

**Comment by SouthHalfCents** [comment]
您发送的邮件我已经收到，我会尽快查看并回复 。 
//明夕何夕0x00 ***@***.***

**Comment by thomasmerz** [comment]
Thanks to [Deepl](https://www.deepl.com/translator#zh/en/%E6%82%A8%E5%8F%91%E9%80%81%E7%9A%84%E9%82%AE%E4%BB%B6%E6%88%91%E5%B7%B2%E7%BB%8F%E6%94%B6%E5%88%B0%EF%BC%8C%E6%88%91%E4%BC%9A%E5%B0%BD%E5%BF%AB%E6%9F%A5%E7%9C%8B%E5%B9%B6%E5%9B%9E%E5%A4%8D%20%E3%80%82%0A%5C%2F%5C%2F%E6%98%8E%E5%A4%95%E4%BD%95%E5%A4%950x00%20***%40***.***) I could understand what you wrote.  So, no need to hurry 👍🏼

**Comment by SouthHalfCents** [comment]
您发送的邮件我已经收到，我会尽快查看并回复 。 
//明夕何夕0x00 ***@***.***
